In [1]:
import pandas as pd
df=pd.read_csv('ecommerce_dataset_+1m.csv')

In [2]:
##Exploratory Data Analysis

In [3]:
df.head()

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
0,ORD-XAJI0,2024-10-14 11:20:05.496679,2024,10,14,11,20,5,No,Completed,...,Email,Mobile,Search,52.1,13,No,45.3,28.66,Medium,Yes
1,ORD-NHJ7X,2024-10-21 00:49:44.681065,2024,10,21,0,49,44,No,Completed,...,Google Ads,Desktop,Referral,36.2,15,No,97.1,33.91,Low,Yes
2,ORD-YTJXE,2025-03-17 19:49:36.983317,2025,3,17,19,49,36,No,Completed,...,Facebook,Tablet,Search,43.1,13,No,43.8,52.77,High,No
3,ORD-EIMVI,2024-09-27 06:24:44.913768,2024,9,27,6,24,44,No,Completed,...,Instagram,Mobile,Direct,39.5,18,Yes,96.9,38.15,Low,Yes
4,ORD-OR56F,2025-05-21 17:10:48.401882,2025,5,21,17,10,48,No,Completed,...,Facebook,Tablet,Social,28.0,3,Yes,45.8,33.05,High,Yes

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000123 entries, 0 to 1000122
Data columns (total 62 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   order_id                  1000123 non-null  object
 1   order_date                1000123 non-null  object
 2   order_year                1000123 non-null  int64
 3   order_month               1000123 non-null  int64
 4   order_day                 1000123 non-null  int64
 5   order_hour                1000123 non-null  int64
 6   order_minute              1000123 non-null  int64
 7   order_second              1000123 non-null  int64
 8   is_weekend                1000123 non-null  object
 9   order_status              1000123 non-null  object
 10  return_reason             99879 non-null    object
 11  customer_id               1000123 non-null  object
 12  customer_name             1000123 non-null  object
 13  gender                    1000123 non-null  object
 14  age                       1000123 non-null  int64
 15  customer_segment          1000123 non-null  object
 16  country                   1000123 non-null  object
 17  city                      1000123 non-null  object
 18  customer_loyalty_score    1000123 non-null  float64
 19  total_orders_by_customer  1000123 non-null  int64
 20  account_creation_date     1000123 non-null  object
 21  product_id                1000123 non-null  object
 22  product_name              1000123 non-null  object
 23  category                  1000123 non-null  object
 24  sub_category              1000123 non-null  object
 25  brand                     1000123 non-null  object
 26  product_rating_avg        1000123 non-null  float64
 27  product_reviews_count     1000123 non-null  int64
 28  stock_quantity            1000123 non-null  int64
 29  unit_price_usd            1000123 non-null  float64
 30  quantity                  1000123 non-null  int64
 31  discount_percent          1000123 non-null  int64
 32  discount_amount_usd       1000123 non-null  float64
 33  total_price_usd           1000123 non-null  float64
 34  cost_usd                  1000123 non-null  float64
 35  profit_usd                1000123 non-null  float64
 36  tax_usd                   1000123 non-null  float64
 37  currency                  1000123 non-null  object
 38  payment_method            1000123 non-null  object
 39  payment_status            1000123 non-null  object
 40  installment_plan          1000123 non-null  object
 41  shipping_method           1000123 non-null  object
 42  shipping_cost_usd         1000123 non-null  float64
 43  delivery_days             1000123 non-null  int64
 44  shipping_country          1000123 non-null  object
 45  warehouse_location        1000123 non-null  object
 46  delivery_status           1000123 non-null  object
 47  rating                    1000123 non-null  int64
 48  review_sentiment          1000123 non-null  object
 49  customer_feedback         800506 non-null   object
 50  coupon_used               1000123 non-null  object
 51  coupon_code               500040 non-null   object
 52  campaign_source           1000123 non-null  object
 53  device_type               1000123 non-null  object
 54  traffic_source            1000123 non-null  object
 55  session_duration_minutes  1000123 non-null  float64
 56  pages_visited             1000123 non-null  int64
 57  abandoned_cart_before     1000123 non-null  object
 58  fraud_risk_score          1000123 non-null  float64
 59  profit_margin_percent     1000123 non-null  float64
 60  order_priority            1000123 non-null  object
 61  support_ticket_created    1000123 non-null  object
dtypes: float64(12), int64(15), object(35)
memory usage: 473.1+ MB

In [5]:
df.describe(include='all')

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,campaign_source,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created
count,1000123,1000123,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1.000123e+06,1000123,1000123,...,1000123,1000123,1000123,1.000123e+06,1.000123e+06,1000123,1.000123e+06,1.000123e+06,1000123,1000123
unique,991930,1000123,NaN,NaN,NaN,NaN,NaN,NaN,2,5,...,6,3,5,NaN,NaN,2,NaN,NaN,3,2
top,ORD-78GK7,2024-10-14 11:20:05.496679,NaN,NaN,NaN,NaN,NaN,NaN,No,Completed,...,Organic,Tablet,Social,NaN,NaN,Yes,NaN,NaN,Low,No
freq,3,1,NaN,NaN,NaN,NaN,NaN,NaN,713021,700232,...,167251,334820,200316,NaN,NaN,500471,NaN,NaN,333899,500237
mean,NaN,NaN,2.024590e+03,6.514849e+00,1.575253e+01,1.148814e+01,2.949467e+01,2.948548e+01,NaN,NaN,...,NaN,NaN,NaN,3.051033e+01,1.050609e+01,NaN,4.996161e+01,3.946517e+01,NaN,NaN
std,NaN,NaN,5.758891e-01,3.448711e+00,8.799790e+00,6.918078e+00,1.730984e+01,1.732781e+01,NaN,NaN,...,NaN,NaN,NaN,1.703368e+01,5.766207e+00,NaN,2.884771e+01,1.094131e+01,NaN,NaN
min,NaN,NaN,2.024000e+03,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,NaN,...,NaN,NaN,NaN,1.000000e+00,1.000000e+00,NaN,0.000000e+00,6.660000e+00,NaN,NaN
25%,NaN,NaN,2.024000e+03,4.000000e+00,8.000000e+00,5.000000e+00,1.400000e+01,1.400000e+01,NaN,NaN,...,NaN,NaN,NaN,1.570000e+01,6.000000e+00,NaN,2.500000e+01,3.169000e+01,NaN,NaN
50%,NaN,NaN,2.025000e+03,7.000000e+00,1.600000e+01,1.100000e+01,3.000000e+01,2.900000e+01,NaN,NaN,...,NaN,NaN,NaN,3.050000e+01,1.100000e+01,NaN,5.000000e+01,3.990000e+01,NaN,NaN
75%,NaN,NaN,2.025000e+03,1.000000e+01,2.300000e+01,1.700000e+01,4.400000e+01,4.400000e+01,NaN,NaN,...,NaN,NaN,NaN,4.530000e+01,1.600000e+01,NaN,7.490000e+01,4.817000e+01,NaN,NaN
max,NaN,NaN,2.026000e+03,1.200000e+01,3.100000e+01,2.300000e+01,5.900000e+01,5.900000e+01,NaN,NaN,...,NaN,NaN,NaN,6.000000e+01,2.000000e+01,NaN,1.000000e+02,6.002000e+01,NaN,NaN

In [6]:
df.isnull().sum().sort_values(ascending=False)

return_reason             900244
coupon_code               500083
customer_feedback         199617
order_id                       0
shipping_method                0
                           ...
product_rating_avg             0
product_reviews_count          0
stock_quantity                 0
unit_price_usd                 0
support_ticket_created         0
Length: 62, dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
##Data Cleaning

In [9]:
df['return_reason'] = df['return_reason'].fillna('No Return')

In [10]:
df['coupon_code'] = df['coupon_code'].fillna('No Coupon')

In [11]:
df['customer_feedback'] = df['customer_feedback'].fillna('No Feedback')

In [12]:
df.isnull().sum().sort_values(ascending=False)

order_id                  0
delivery_status           0
total_price_usd           0
cost_usd                  0
profit_usd                0
                         ..
brand                     0
product_rating_avg        0
product_reviews_count     0
stock_quantity            0
support_ticket_created    0
Length: 62, dtype: int64

In [13]:
df['customer_feedback'].value_counts()

customer_feedback
No Feedback             199617
Could be better         100591
Excellent!              100325
Highly recommended      100315
Average quality         100148
Fast delivery           100111
Not satisfied            99971
Great product!           99538
Good value for money     99507
Name: count, dtype: int64

In [14]:
df[['coupon_code','customer_feedback','return_reason']].head(10)

  coupon_code     customer_feedback     return_reason
0     CPN-ZBI           No Feedback         No Return
1     CPN-W2P  Good value for money         No Return
2     CPN-J5P    Highly recommended         No Return
3     CPN-5C3    Highly recommended         No Return
4     CPN-YLJ       Average quality         No Return
5     CPN-E8Y       Could be better  Not As Described
6   No Coupon            Excellent!         No Return
7   No Coupon    Highly recommended         No Return
8   No Coupon       Average quality         No Return
9     CPN-DP5           No Feedback         No Return

In [15]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [16]:
df['unit_price_usd'] = df['unit_price_usd'].astype(float)

In [17]:
print(df['order_date'].dtype)

datetime64[ns]

In [18]:
##Feature Engeneering

In [19]:
df['order_frequency'] = df.groupby('order_id')['order_id'].transform('count')

In [20]:
##Investigating if orders are duplicates or is it synthetic data same ID repeated

In [21]:
df[df['order_frequency'] > 1].sort_values('order_id')

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created,order_frequency
726923,ORD-008WV,2025-02-08 05:49:03.813844,2025,2,8,5,49,3,Yes,Completed,...,Tablet,Email,26.8,13,No,17.0,44.52,Medium,Yes,2
958078,ORD-008WV,2024-12-07 17:00:22.429434,2024,12,7,17,0,22,Yes,Completed,...,Tablet,Referral,29.2,4,No,24.3,35.53,Low,No,2
881574,ORD-00B89,2025-04-21 03:30:09.548645,2025,4,21,3,30,9,No,Completed,...,Desktop,Search,48.2,11,Yes,4.0,47.30,Low,Yes,2
611006,ORD-00B89,2024-12-03 19:12:49.590163,2024,12,3,19,12,49,No,Completed,...,Tablet,Search,16.3,12,Yes,72.5,59.45,Medium,Yes,2
681574,ORD-00EJ3,2024-04-28 06:40:37.901501,2024,4,28,6,40,37,Yes,Pending,...,Mobile,Social,27.0,4,Yes,51.3,44.74,Low,Yes,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552710,ORD-ZZJJ7,2024-04-09 22:41:34.577359,2024,4,9,22,41,34,No,Completed,...,Tablet,Social,49.6,14,Yes,22.1,51.09,Low,Yes,2
302626,ORD-ZZK0O,2025-10-03 00:36:43.159160,2025,10,3,0,36,43,No,Completed,...,Desktop,Email,58.5,10,No,39.0,31.88,Medium,Yes,2
356634,ORD-ZZK0O,2024-03-07 11:38:51.921859,2024,3,7,11,38,51,No,Completed,...,Desktop,Social,28.8,13,Yes,77.8,25.70,Medium,Yes,2
768760,ORD-ZZV4N,2024-11-15 07:31:40.649683,2024,11,15,7,31,40,No,Completed,...,Mobile,Social,53.2,9,Yes,17.7,55.56,Medium,Yes,2
618316,ORD-ZZV4N,2025-07-05 15:39:55.043639,2025,7,5,15,39,55,Yes,Completed,...,Tablet,Direct,43.4,15,Yes,61.7,34.03,Medium,Yes,2

In [22]:
df[df.duplicated(subset=['order_id'], keep=False)]

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created,order_frequency
13,ORD-DIUOV,2024-04-06 15:39:08.276012,2024,4,6,15,39,8,Yes,Completed,...,Mobile,Direct,10.8,10,No,43.9,51.51,Medium,No,2
197,ORD-4E2U2,2024-03-31 19:46:12.825996,2024,3,31,19,46,12,Yes,Completed,...,Tablet,Referral,25.9,4,No,92.0,49.49,High,No,2
203,ORD-OM5FK,2024-12-15 23:17:20.504002,2024,12,15,23,17,20,Yes,Completed,...,Desktop,Search,2.3,2,Yes,77.4,25.92,Low,No,2
222,ORD-ZW5AP,2024-02-19 13:06:46.901837,2024,2,19,13,6,46,No,Completed,...,Desktop,Search,48.3,15,No,16.5,47.22,Low,Yes,2
268,ORD-V5LMQ,2025-12-03 02:09:15.741350,2025,12,3,2,9,15,No,Pending,...,Desktop,Direct,14.3,15,Yes,83.4,28.80,Low,Yes,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999949,ORD-TSAGZ,2025-06-17 10:34:35.823489,2025,6,17,10,34,35,No,Completed,...,Desktop,Social,36.6,17,No,3.4,40.06,Low,No,2
999962,ORD-GPLJB,2025-05-14 09:15:36.955485,2025,5,14,9,15,36,No,Completed,...,Tablet,Referral,25.0,8,Yes,24.1,48.84,High,Yes,2
999990,ORD-QDSEU,2025-02-23 20:44:12.363859,2025,2,23,20,44,12,Yes,Completed,...,Tablet,Direct,49.4,3,No,71.9,31.81,Low,Yes,2
1000025,ORD-CP747,2024-02-16 20:05:17.002084,2024,2,16,20,5,17,No,Pending,...,Tablet,Direct,40.6,18,Yes,50.0,41.59,High,No,2
1000102,ORD-67B78,2025-08-04 04:48:12.336495,2025,8,4,4,48,12,No,Completed,...,Tablet,Referral,47.9,19,No,33.5,54.18,High,No,2

In [23]:
df[df['order_id'] == 'ORD-DIUOV']

,order_id,order_date,order_year,order_month,order_day,order_hour,order_minute,order_second,is_weekend,order_status,...,device_type,traffic_source,session_duration_minutes,pages_visited,abandoned_cart_before,fraud_risk_score,profit_margin_percent,order_priority,support_ticket_created,order_frequency
13,ORD-DIUOV,2024-04-06 15:39:08.276012,2024,4,6,15,39,8,Yes,Completed,...,Mobile,Direct,10.8,10,No,43.9,51.51,Medium,No,2
702340,ORD-DIUOV,2025-11-05 04:47:09.598204,2025,11,5,4,47,9,No,Completed,...,Desktop,Referral,33.7,16,Yes,19.1,45.01,Low,Yes,2

In [24]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, order_year, order_month, order_day, order_hour, order_minute, order_second, is_weekend, order_status, return_reason, customer_id, customer_name, gender, age, customer_segment, country, city, customer_loyalty_score, total_orders_by_customer, account_creation_date, product_id, product_name, category, sub_category, brand, product_rating_avg, product_reviews_count, stock_quantity, unit_price_usd, quantity, discount_percent, discount_amount_usd, total_price_usd, cost_usd, profit_usd, tax_usd, currency, payment_method, payment_status, installment_plan, shipping_method, shipping_cost_usd, delivery_days, shipping_country, warehouse_location, delivery_status, rating, review_sentiment, customer_feedback, coupon_used, coupon_code, campaign_source, device_type, traffic_source, session_duration_minutes, pages_visited, abandoned_cart_before, fraud_risk_score, profit_margin_percent, order_priority, support_ticket_created, order_frequency]
Index: []

[0 rows x 63 columns]

In [25]:
df['total_revenue'] = df['unit_price_usd'] * df['quantity']

In [26]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in e:\anaconda\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in e:\anaconda\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in e:\anaconda\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in e:\anaconda\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [27]:
from sqlalchemy import create_engine

username = 'postgres'
password = 'Post12'
host = 'localhost'
port = '5432'
database = 'customer_behaviour'

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = 'customer'

df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.